version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: cdn_postgres
    restart: always
    environment:
      POSTGRES_USER: cdn_user
      POSTGRES_PASSWORD: cdn_password
      POSTGRES_DB: cdn_metadata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cdn-node:
    build:
      context: ./cdn-server
      dockerfile: Dockerfile
    container_name: cdn_node_1
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./cdn-server/data/storage:/app/data/storage
      - ./cdn-server/data/db:/app/data/db
    environment:
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  pgdata:
